apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: post-pusher-kafka
  namespace: kubernetes-project
spec:
  project: default
  source:
    repoURL: https://github.com/mathias-rosa/cours_kubernetes.git
    targetRevision: main
    path: post_pusher
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
